### ISSUE TITLE
Tabs being mixed with spaces

### ISSUE THREAD

**Issue by Strilanc** [ProjectQ-Framework/ProjectQ#12]
Many files in the project have spaces hidden amongst the tabs. Sometimes by accident, sometimes on purpose for fine-grained alignment (despite that not making any sense with tabs present).

Given that PEP8 strongly recommends spaces, we should probably switch to spaces.

**Comment by damiansteiger** [comment]
We started out by using tabs because it give the user more freedom. You can either set the tab width to be 2 spaces or 4 spaces in your editor of choice.

If you then want fine-grained alignment, it needs to be mixed: As many tabs as the line above and then spaces s.t. the alignment is correct for both tab width 4 or tab width 2.

We are currently considering to move to spaces, so thanks for your input.

In any case, we should add an automatic linter to check all new commits and clean up the old code. I am not sure if there is a linter which can handle tabs + spaces (for fine-grained alignment)...

**Comment by maffoo** [comment]
+1 for spaces in python code. They're essentially universal for python, and using tabs will likely create friction for python devs. For c++ code tabs are fine, though my personal preference would be for spaces there too... :-)

**Comment by damiansteiger** [comment]
@Strilanc @maffoo: As we are deciding this issue in the next days, we would like to get your input:

I understand that you both have a strong preference for spaces over tabs. Any preference on 4 vs 2 spaces? (I currently show my tabs as 4 spaces)

Also while we are already on it, we can also discuss line width. While PEP says 79 characters, I often find this a bit short...

**Comment by Strilanc** [comment]
4 spaces is more common, and your existing alignments are set up based on tabs being 4 spaces (making the transition trivial), so I would go with 4.

I don't have any strong line width preferences. My preference literally changes monitor by monitor. I guess I wouldn't go lower than 79 or higher than 160. For a physics thing, 137 is kind of tempting...

**Comment by thomashaener** [comment]
I'm currently using 2 spaces, but our alignments work with any tab-width; this is why we mixed tabs and spaces for aligning multi-line statements:
```
...
\t\tsome_function_with_many_parameters(param1,
\t\t                                   param2,
...
```
I would be fine using 4 spaces, though.

As for the width: 137 would indeed be tempting :) but it's probably a bit too long; I'm ok with PEP8.

**Comment by Strilanc** [comment]
Oh, you were careful that all semantic indentation was tabs and all alignment was spaces? Then nevermind the point about preferring 4 for that reason.

**Comment by maffoo** [comment]
I would suggest 4 spaces, since that is the python standard and most projects indent that way (also python-aware editors and other tools will default to that, etc.).

I don't have a strong preference for line length, the best thing is just to pick something and stick with it (and ideally have a linter in place to enforce it). For reference, the google style guides for [python](https://google.github.io/styleguide/pyguide.html#Line_length) and [c++](https://google.github.io/styleguide/cppguide.html#Line_Length) say 80 characters, while the [java](https://google.github.io/styleguide/javaguide.html#s4.4-column-limit) style guide says 100 characters (not surprisingly, since java tends to be verbose).

**Comment by damiansteiger** [comment]
We decided to follow the PEP8 guide and change indentation to 4 spaces and enforce a line width to 79 characters. Thanks @thomashaener for manually changing and checking everything and @Strilanc for bringing up this issue
