### ISSUE TITLE
Controlled Time Evolution Gate with 3+ Control Qubits

### ISSUE THREAD

**Issue by erikweis** [ProjectQ-Framework/ProjectQ#183]
I am trying to implement a circuit to do eigenvalue estimation for some QubitOperator. When I run the circuit with 2 control bits, the circuit works fine. However, when I try using 3 control bits, I get the following error:

**Mapping without SWAPs failed! Sorry...**

Additionally, I get this error message when only apply a controlled gate to one of the qubits in the 'wave function' and not the other. Any ideas? Thanks!

[qft_test.txt](https://github.com/ProjectQ-Framework/ProjectQ/files/1425384/qft_test.txt)

**Comment by damiansteiger** [comment]
> Mapping without SWAPs failed! Sorry...

IBM's hardware has a limited connectivity between the qubits, i.e., there are only certain pairs of qubit ids which can perform a two qubit gate such as a CNOT. This error message means, that for this particular circuit, the compiler cannot map it to the hardware layout without using SWAP operations. Currently the hardware is too noisy in order to perform such swap operations and run a reasonably large algorithm, hence you get this error message instead.

* If you still want to run it on their hardware, you need to manually insert SWAP operations in order to satisfy their hardware layout

Another mistake I have spotted is that you are specifying to run on the 16 qubit chip (ibmqx5). Therefore, you need to do all the mapping manually as opposed to the 5 qubit chip for which the compiler automatically tries to find a mapping (without using SWAP gates). An example is shown in the examples folder:
[ibm16.py](https://github.com/ProjectQ-Framework/ProjectQ/blob/develop/examples/ibm16.py)

If you are interested in algorithm development,  I would suggest to use the standard simulator in ProjectQ as you won't run into mapping issues.

By the way a few other mistakes in your code:
* Measure is a single qubit gate, hence if you want to apply it to a quantum register with more than one qubits, you should use All()

```
import math

from projectq import MainEngine
from projectq.backends import Simulator
from projectq.ops import Measure, H, QubitOperator, QFT, get_inverse, TimeEvolution, Swap, All
from projectq.meta import Control, Loop

def qft_test(eng):
	control_qubits=eng.allocate_qureg(3)
	psi=eng.allocate_qureg(2)

	hamiltonian=QubitOperator('X0 X1')
	iQFT=get_inverse(QFT)

	QFT | control_qubits

	with Control(eng,control_qubits[0]):
		TimeEvolution(time=3.0,hamiltonian=hamiltonian)|psi

	with Control(eng,control_qubits[1]):
		TimeEvolution(time=4.0,hamiltonian=hamiltonian)|psi

	with Control(eng,control_qubits[2]):
		TimeEvolution(time=4.0,hamiltonian=hamiltonian)|psi

	iQFT|control_qubits

	eng.flush() # Important before accessing the simulator backend (see tutorial)
	print(eng.backend.get_probability('00111',control_qubits+psi)) # Or any other fancy method explained in the simulator tutorial

	All(Measure)|control_qubits
	All(Measure)|psi

	eng.flush()


if __name__ == '__main__':
	eng=MainEngine(backend=Simulator())
	qft_test(eng)

```
