### ISSUE TITLE
Unexpected scope for default_engines

### ISSUE THREAD

**Issue by kevinsung** [ProjectQ-Framework/ProjectQ#191]
I discovered that after executing the statement
```
import projectq
```
the `setups` and `default_engines` module are still not available, even though the rest are. This was quite confusing to me when I was using the compiler tutorial as a template, since the statement
```
projectq.default_engines()
```
wouldn't work for me. It took me some time to figure out that in the tutorial, the reason it works is that the statement
```
eng = projectq.MainEngine(backend=CommandPrinter(accept_input=False))
```
was executed earlier, and this is due to the lines
```
if engine_list is None:
    try:
        engine_list = projectq.default_engines()
    except AttributeError:
        from projectq.setups.default import default_engines
        engine_list = default_engines()
```
in the `__init__` function of `MainEngine`.

This behavior seems undesirable because it's not transparent when the statement `projectq.default_engines()` becomes available. One solution would be to make it clear somewhere (perhaps in `projectq/__init__.py` what modules we want to expose to people. I still don't understand how the modules are getting exposed.

**Comment by thomashaener** [comment]
Yes, the reason for this is that we are still using `import projectq.setups.xxx` to load setups, instead of having it as a function which would also make it possible to switch back and forth between setups in the same run.
The problem is that this would be a breaking change, same as the improved error handling (depending on how it will be implemented). In any case, these two changes are planned for the next release.
