### ISSUE TITLE
Error in example: TypeError: __init__() got an unexpected keyword 'setup'

### ISSUE THREAD

**Issue by melgu** [ProjectQ-Framework/ProjectQ#232]
When I try to run the examples using the IBM quantum computer (Instead of the simulation), I always get the following (or similar) error message:

```
Exception AttributeError: "'MainEngine' object has no attribute 'next_engine'" in <bound method MainEngine.__del__ of <projectq.cengines._main.MainEngine object at 0x1070eb2d0>> ignored
Traceback (most recent call last):
  File "/Users/melvin/Downloads/ProjectQ-develop/examples/quantum_random_numbers_ibm.py", line 7, in <module>
    eng = MainEngine(IBMBackend(), setup=projectq.setups.ibm)
TypeError: __init__() got an unexpected keyword argument 'setup'
```

**Comment by damiansteiger** [comment]
Hi,

This error is probably caused because you have installed ProjectQ via pip which installs the latest version of the [master branch](https://github.com/ProjectQ-Framework/ProjectQ/tree/master). So you should go and run the examples from the master branch as they are compatible with your installed version of ProjectQ (which does not yet have a `setup` parameter for the MainEngine)

Unfortunately, IBM has changed in the meantime since your latest update of master branch (and hence the latest projectq version on pip) their chip specs: one CNOT goes now the other direction which would cause errors. This is right now being fixed in #231 

So your options right now are:
* Wait for a day until #231 is merged into the develop branch and install that version of ProjectQ as described in the docs
* Install ProjectQ using the branch of #231: then things are working right now
* In probably about a week we have ProjectQ 0.3.6->0.4 which you can then also pip install and everything should work fine

Note:
* In the meantime we are probably exchanging this setup parameter before the next release of version 0.4, see #233 
* The IBM chip has currently long queues. We will add a mechanism to deal with this issue soon. (As currently ProjectQ aborts if it has to wait a certain amount of time and has not yet got the results back)

**Comment by damiansteiger** [comment]
FYI: #231 and #233 have been merged into the develop branch. So the easiest solution (until the release of version 0.4) is to install the develop version of ProjectQ and then your IBM hardware runs should work fine provided that the queue at IBM is not too long (a new feature handling this is coming soon)

**Comment by damiansteiger** [comment]
The new release of ProjectQ v0.4 is out. Please install that version and everything should work fine.
