### ISSUE TITLE
Too many non-reverted Computes causes a recursion error

### ISSUE THREAD

**Issue by refi64** [ProjectQ-Framework/ProjectQ#344]
I found this to be really confusing:

```python
from projectq.ops import Measure
import projectq
import projectq.meta

eng = projectq.MainEngine()
q0 = eng.allocate_qubit()

for i in range(1000):
    with projectq.meta.Compute(eng):
        pass

Measure | q0
```

yields:

```
Traceback (most recent call last):
  File "bell_state.py", line 12, in <module>
    Measure | q0
  File "/var/home/ryan/.virtualenvs/projectq/lib/python3.7/site-packages/projectq/ops/_gates.py", line 284, in __or__
    apply_command(cmd)
  File "/var/home/ryan/.virtualenvs/projectq/lib/python3.7/site-packages/projectq/ops/_command.py", line 58, in apply_command
    engine.receive([cmd])
  File "/var/home/ryan/.virtualenvs/projectq/lib/python3.7/site-packages/projectq/cengines/_main.py", line 266, in receive
    self.send(command_list)
  File "/var/home/ryan/.virtualenvs/projectq/lib/python3.7/site-packages/projectq/cengines/_main.py", line 288, in send
    raise compact_exception  # use verbose=True for more info
RecursionError: maximum recursion depth exceeded
 raised in:
'  File "/var/home/ryan/.virtualenvs/projectq/lib/python3.7/site-packages/projectq/meta/_compute.py", line 247, in receive'
'    self.send(command_list)'
```

The most bizarre part is that it errors on the `Measure` statement. I had commented out an Uncompute block for testing something but forgot to comment the compute, then it took me a few moments to figure out where the error was.

**Comment by Takishima** [comment]
The reason you get the recursion error stems from the way the context manager is implemented in the case of the `Compute`/`Uncompute`/`CustomUncompute` statements. This needs a bit of context to be fully understood. 

The way a `Compute` context manager works in ProjectQ is that it inserts a `ComputeEngine` compiler engine right after the `MainEngine` in the engine list. This new engine basically records all the commands that pass through it so that these may be properly uncomputed in the future. Upon exiting the `Compute` region, this engine is not immediately dropped. Instead, the `ComputeEngine` gets dropped in the `Uncompute`/`CustomUncompute` region, which is not present in your case.

This essentially means that you have a list of 1000 `ComputeEngine` that are right after the `MainEngine` and each time a command gets sent by the `MainEngine` it calls the `send` method, which itself calls the `receive` method of `CompilerEngine`, which essentially lead to a recursion depth larger than what Python allows by default.

I believe the main reason this was implemented so was to allow an easy way to check that upon reaching an `Uncompute`/`CustomUncompute` region, a corresponding `Compute` region exists.

**Comment by refi64** [comment]
Could maybe there be a check that the size doesn't exceed some fixed
amount, e.g. like 100 or so?

**Comment by Takishima** [comment]
Sure that would be something fairly easy to implement. I don't know when I'll have the time to get to implementing it though.
